version: "3"
services:
  paco-api:
    container_name: Paco Drawing API
    restart: unless-stopped
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "4000:4000"

  paco-redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001

volumes:
  paco-api:
