FORMAT: 1A

# Paco API Implementation

This is a read-only API, only GET requests are valid.

# Character [/character/paco-panda]

## Get character [GET]
+ Response 200 (application/json)
  + Body
  {
    "slug": "paco-panda",
    "name": "Paco",
    "species": "Panda",
    "is_hybrid": false,
    "stats": {
      "7d": 6,
      "30d": 51,
      "total": 1004
    },
    "appearances": {
      "endpoint": "<HOST>/character/paco-panda/appearances"
      "items": [
        {
          "slug": "artwork-name",
          "name": "ARTWORK_NAME",
          "description": "...",
          "date": "2000-01-01T00:00:00Z",
          "characters": [
            {
              "slug": "paco-panda",
              "name": "Paco",
              "species": "Panda",
              "is_hybrid": false
            },
            {
              "slug": "roni-dog",
              "name": "Roni",
              "species": "Dog",
              "is_hybrid": false
            }
          ],
          "tags": ["..."]
        },
        {
          "slug": "artwork-name",
          "name": "ARTWORK_NAME",
          "description": "...",
          "date": "2000-01-01T00:00:00Z",
          "characters": [
            {
              "slug": "paco-panda",
              "name": "Paco",
              "species": "Panda",
              "is_hybrid": false
            },
            {
              "slug": "yaps-fox",
              "name": "Yaps",
              "species": "Fox",
              "is_hybrid": false
            }
          ],
          "tags": ["..."]
        }
      ]
    }
  }