#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged

if ! command -v autopep8 >nul 2>&1; then
  pip install autopep8
fi

autopep8 --in-place --recursive --verbose --exclude "venv,__pycache__,.mypy_cache" python
