on:
  schedule:
    - cron "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout actions
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
        - name: execute python script
          run: |
            python -m pip install --upgrade pip
        

