name: Python Typing & Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  type-check:
    name: Type-checking via mypy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          mypy --install-types

      - name: Type-check scripts
        run: mypy .
